baseurl: "/Handbuch-Jugend-Hackathons"

collections:
    chapters_de:
        output: true
        permalink: /chapters_de/:path/
        language: de
    chapters_nl:
        output: true
        permalink: /chapters_nl/:path/
        language: nl
    chapters_en-US:
        output: true
        permalink: /chapters_en-US/:path/
        language: en-US

defaults:
  - scope:
        type: chapters_de
    values:
        layout: chapter
  - scope:
        type: chapters_nl
    values:
        layout: chapter
  - scope:
        type: chapters_en-US
    values:
        layout: chapter
